globals:
  variables:
    project-name:
      question: What should the project name be?
      validation: "^[\\w-]+$"
    cleanup-clonr:
      question: Do you want to remove the .clonr-config.yml file? 
      choices: 
        - "yes"
        - "no"
    typescript:
      question: Do you want to use TypeScript?
      choices:
        - "yes"
        - "no"
    pwa:
      question: Do you want to set up a PWA?
      choices:
        - "yes"
        - "no"
    hello-world-message:
      question: What do you want your hello world message to be?
    app-preference:
      question: Do you prefer class components or functional components?
      choices:
        - Class
        - Function

templates:
  package.json:
    location: /package.json
    variables:
      globals:
      project-version:
        question: What should the project's starting version be?
        default: 1.0.0
        validation: "^v?\\d+\\.\\d+\\.\\d+$"
      project-description:
        question: Please provide a one line description for the project.
      author:
        question: Who is the author of the project?
      license:
        question: What type of license?

  src/root.component.js:
    location: /src/root.component.js
    condition: clonrResult = !(getClonrVar("globals[typescript]") === "yes")
    variables:
      test:
        question: Press Enter.


  src/root.component.tsx:
    location: /src/root.component.tsx
    condition: clonrResult = (getClonrVar("globals[typescript]") === "yes")
    variables:
      test:
        question: Press Enter.

  src/index.js:
    location: /src/index.js
    variables:
      test:
        question: Press Enter.

  # Clean up clonr files
  .clonr-config.yml:
    location: /.clonr-config.yml
    condition: clonrResult = !(getClonrVar("globals[cleanup-clonr]") === "yes")
  README.md:
    location: /README.md
    variables:
      test:
        question: Press Enter.
